#!/usr/bin/env bash
# Transfer a file to a server
if (("$#" < 4)); then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp "$1" -o StrictHostKeyChecking=no "$3@$2":~/"$4"
fi
