#!/usr/bin/env bash
# Nginx redirects to another page and must be 301 Moved Permanently

sudo apt-get update;
sudo apt-get -y install nginx;

sudo mkdir /etc/nginx/html;

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default;
sudo service nginx restart
