#!/usr/bin/env bash
# Make the page return a custum 404 page

sudo apt-get update;
sudo apt-get -y install nginx;
sudo mkdir /etc/nginx/html;
sudo touch /etc/nginx/html/index.html;
sudo touch /etc/nginx/html/404.html
echo "Hello World!" >> /etc/nginx/html/index.html;
echo "Ceci n'est pas une page" >> /etc/nginx/404.html
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    error_page 404 /404.html
    index index.html;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
" > /etc/nginx/sites-available/default;
sudo service nginx restart
