#!/usr/bin/env bash
# Make the page return a custum 404 page

sudo apt-get update;
sudo apt-get -y install nginx;

sudo mkdir /etc/nginx/html;
sudo touch /etc/nginx/html/40x.html

echo "Ceci n'est pas une page" >> /etc/nginx/40x.html;
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    error_page 404 /40x.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location = 404.html {
        root /etc/nginx/html;i
        internal;
    }
}
" > /etc/nginx/sites-available/default;

sudo service nginx restart
