#!/usr/bin/env bash
# header response

apt-get update -y;
apt-get install -y nginx;

mkdir /etc/nginx/html;
touch /etc/nginx/html/index.html;
touch /etc/nginx/html/40x.html
echo "Hello World!" >> /etc/nginx/html/index.html;
echo "Ceci n'est pas une page" >> /etc/nginx/html/40x.html;
printf %s "server {
  listen 80 default_server;
  listen [::]:80 default_server;
  root /etc/nginx/html;
  index index.html;
  error_page 404 /40x.html;
  add_header X-Served-By $HOSTNAME;
  location /redirect_me {
    return 301 https://i.imgur.com/guDXtsC.png;
  }
  location = /40x.html {
      root /etc/nginx/html;
      internal;
  }
}
" > /etc/nginx/sites-available/default;

sudo service nginx restart

