#!/usr/bin/env bash
# Install and configure HAproxy on 1b-01 server

sudo apt update -y;
sudo apt upgrade -y;
sudo apt-get -y install haproxy;
sudo sed -i "$ aENABLED=1" /etc/init.d/haproxy;

printf %s "
frontend myfrontend
    bind *:80
    default_backend myservers
  
backend myservers
    server 4517-web-01 52.23.203.134
    server 4517-web-02 50.19.56.156
    timeout connect 5s
    timeout server 10s
    balance roundrobin
    mode http" >> /etc/haproxy/haproxy.cfg;
sudo service haproxy restart
