#!/usr/bin/env bash
#comments
h=0
m=60

while [ $h -le 12 ];
do
    if [[ $m -eq 60 ]]
    then
        echo "Hour: $h"
        ((h++))
        m=1
    else
        echo $m
        ((m++))
    fi
done

