#!/usr/bin/env bash
# Install and configure ufw to only allow pecific TCP ports

sudo apt-get update -y;
sudo apt-get -y install ufw;

ufw default deny incoming;

ufw allow 22;
ufw allow 443;
ufw allow 80;

ufw enable
