#!/usr/bin/env bash
# Redirects port 8080/TCP to post 80/TCP on web-01

sudo apt-get update -y;
sudo apt-get -y install ufw;

ufw default deny incoming;

ufw allow 22;
ufw allow 443;
ufw allow 80;
uwf allow 8080/tcp;

echo -e "
*nat
:PREROUTING ACCEPT [0:0]
-A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 8080
COMMIT\n$(cat /etc/ufw/before.rules)" > /etc/ufw/before.rules;

ufw --force enable
